# ог , 0 0=>0 , 0 1=>1 , 1 0=> 1 , 1 1=>1
# not 0=> 1, 1=> 0
# and , 0 8 => 0, 0 1=> 0, 1 0=> 0, 1 1->1 I

# num1=10
# print (num1>0)
# print (num1<15)
# print(num1>0 and num1<15)
# print (numi‹0)
# print (num1<15)
# print (numic@ and numi<15)
# print(num1<8)
# print (num1>15)
# print (num1<0 and num1>15)
#  (num1>0)
# print (num1>15)
# printprint (num1>0 and num1>15)
# print the height and weight ratio => height<157 ,weight<55 => true

# height=120
# weight=45
# print(height<150)
# print(weight<50)
# print(height<150 and weight<50)


height=120
weight=45
print(height<150)
print(weight<50)
print(height<150 and weight<50)

height=120
weight=45
print(height<150)
print(weight<50)
print(height>150 and weight<50)

height=120
weight=45
print(height<150)
print(weight<50)
print(height>150 and weight>50)

height=120
weight=45
print(height<150)
print(weight>50)
print(height>50 and weight<50)

height=120
weight=45
print(height>150)
print(weight<50)
print(height>150 and weight>50)

height=120
weight=45
print(height<150)
print(weight<50)
print(height<150 or weight<50)

height=120
weight=45
print(height<150)
print(weight<50)
print(height>150 or weight<50) 

height=120
weight=45
print(height<150)
print(weight<50)
print(height>150 or weight>50)

height=120
weight=45
print(height<150)
print(weight>50)
print(height>50 or weight<50)

height=120
weight=45
print(height>150)
print(weight<50)
print(height>150 or weight>50)

